---
- name: install fail2ban
  yum:
    name: fail2ban
    state: present

- name: setup fail2ban configuration
  template:
    dest: /etc/fail2ban/jail.local
    src: jail.local.j2
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload fail2ban

- name: ensure fail2ban is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes
